version: '3.8'

services:
  backend:
    build:
      context: ./TaskManagerAPI/TaskManagerAPI
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Data Source=/app/Data/taskmanager.db
    volumes:
      - backend_data:/app/Data
    container_name: taskmanager-backend-dev
    restart: unless-stopped

  frontend:
    build:
      context: ./taskmanager-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    depends_on:
      - backend
    container_name: taskmanager-frontend-dev
    restart: unless-stopped

volumes:
  backend_data: